package com.incture.accpay.util;

public class APEnum {
	
	 public enum Status{SUCCESS,ERROR,WIP,FAILURE,DRAFT,REJECTED};
	 public enum Matching{FULL_MATCH,UNIT_PRICE_MISMATCH,QUNATITY_MISMATCH};
	 public enum Steps{EMAIL_PROCESSING,OCR_PROCESSING,BPM_TRIGGER,PO_PROCESSING,TWO_WAY_MATCHING,THREE_WAY_MATCHING,REVEIW_INVOICE,APPROVE_INVOICE,POST_INVOICE, RECEIVING_TEAM};
	 
}
